name: YOCaml Deploy Documentation
on:
  push:
    branches:
      - main

jobs:
  build_opam:
    name: opam build & run tests
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        ocaml-compiler:  [ ocaml-base-compiler.5.3.0 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout Tree
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune build @install
      - run: opam install odoc-driver
      - run: opam exec -- dune exec -- odoc_driver yocaml yocaml_eio yocaml_unix yocaml_git yocaml_cmarkit yocaml_markdown yocaml_jingoo yocaml_mustache yocaml_omd yocaml_otoml yocaml_runtime yocaml_syndication yocaml_yaml --remap

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_html/
          external_repository: yocaml/doc
          publish_branch: gh-pages
          enable_jekyll: false
